# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_dir.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(442, 110)
        self.dir_name = QtWidgets.QLineEdit(widget)
        self.dir_name.setGeometry(QtCore.QRect(50, 20, 351, 31))
        self.dir_name.setObjectName("dir_name")
        self.buttonBox = QtWidgets.QDialogButtonBox(widget)
        self.buttonBox.setGeometry(QtCore.QRect(140, 60, 161, 41))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "创建文件夹"))
